CREATE DATABASE Hubvenue;

USE Hubvenue;

CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	usertype VARCHAR(10) NOT NULL,
	username VARCHAR(50) NOT NULL,
	email VARCHAR(20) UNIQUE NOT NULL,
	password VARCHAR(20) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
